### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by AndraiNardo** [ADOFAI-gg/CosmicLoader#7]
there is no documentation on how to install this software anywhere on the intrenet as far as i am aware off, it would be grate knowing how to install this software.

**Comment by AndraiNardo** [comment]
found the documentation on how to install on your discord

**Comment by ppapman1** [comment]
Cosmic Loader has not been released yet

**Comment by CrackThrough** [comment]
If you're going to mod a game with this software, please do not use this before the >=0.1.0 release. The features are incomplete and there is little to no practical use yet. Instead, we advise you to use [UnityModManager](https://github.com/newman55/unity-mod-manager) when modding ADOFAI as it is a community standard for now.
